name: Build and Test iOS App

on: [workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: List installed Xcode versions
      run: ls /Applications | grep Xcode

    - name: Select Xcode version
      run: sudo xcode-select -s /Applications/Xcode_26.0.app/Contents/Developer

    - name: Install dependencies
      run: pod install

    - name: Build the app
      run: xcodebuild build -scheme "OpenEdXProd" -destination "platform=iOS Simulator,name=iPhone 13"

    - name: Run tests
      run: xcodebuild test -scheme "OpenEdXProd" -destination "platform=iOS Simulator,name=iPhone 13"